/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReachRouteImport } from './routes/reach'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardStatsRouteImport } from './routes/_authenticated/dashboard.stats'
import { Route as AuthenticatedDashboardProofsRouteImport } from './routes/_authenticated/dashboard.proofs'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPortfolioRouteImport } from './routes/_authenticated/dashboard.portfolio'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardLiquidityRouteImport } from './routes/_authenticated/dashboard.liquidity'
import { Route as AuthenticatedDashboardDiscoverRouteImport } from './routes/_authenticated/dashboard.discover'
import { Route as AuthenticatedDashboardAgentsRouteImport } from './routes/_authenticated/dashboard.agents'
import { Route as AuthenticatedDashboardProofsProofIdRouteImport } from './routes/_authenticated/dashboard.proofs.$proofId'
import { Route as AuthenticatedDashboardOrdersOrderIdRouteImport } from './routes/_authenticated/dashboard.orders.$orderId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStatsRoute =
  AuthenticatedDashboardStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProofsRoute =
  AuthenticatedDashboardProofsRouteImport.update({
    id: '/proofs',
    path: '/proofs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPortfolioRoute =
  AuthenticatedDashboardPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLiquidityRoute =
  AuthenticatedDashboardLiquidityRouteImport.update({
    id: '/liquidity',
    path: '/liquidity',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDiscoverRoute =
  AuthenticatedDashboardDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentsRoute =
  AuthenticatedDashboardAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProofsProofIdRoute =
  AuthenticatedDashboardProofsProofIdRouteImport.update({
    id: '/$proofId',
    path: '/$proofId',
    getParentRoute: () => AuthenticatedDashboardProofsRoute,
  } as any)
const AuthenticatedDashboardOrdersOrderIdRoute =
  AuthenticatedDashboardOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedDashboardOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/reach': typeof ReachRoute
  '/roadmap': typeof RoadmapRoute
  '/studio': typeof StudioRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/agents': typeof AuthenticatedDashboardAgentsRoute
  '/dashboard/discover': typeof AuthenticatedDashboardDiscoverRoute
  '/dashboard/liquidity': typeof AuthenticatedDashboardLiquidityRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRouteWithChildren
  '/dashboard/portfolio': typeof AuthenticatedDashboardPortfolioRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/proofs': typeof AuthenticatedDashboardProofsRouteWithChildren
  '/dashboard/stats': typeof AuthenticatedDashboardStatsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/orders/$orderId': typeof AuthenticatedDashboardOrdersOrderIdRoute
  '/dashboard/proofs/$proofId': typeof AuthenticatedDashboardProofsProofIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/reach': typeof ReachRoute
  '/roadmap': typeof RoadmapRoute
  '/studio': typeof StudioRoute
  '/dashboard/agents': typeof AuthenticatedDashboardAgentsRoute
  '/dashboard/discover': typeof AuthenticatedDashboardDiscoverRoute
  '/dashboard/liquidity': typeof AuthenticatedDashboardLiquidityRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRouteWithChildren
  '/dashboard/portfolio': typeof AuthenticatedDashboardPortfolioRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/proofs': typeof AuthenticatedDashboardProofsRouteWithChildren
  '/dashboard/stats': typeof AuthenticatedDashboardStatsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/orders/$orderId': typeof AuthenticatedDashboardOrdersOrderIdRoute
  '/dashboard/proofs/$proofId': typeof AuthenticatedDashboardProofsProofIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/reach': typeof ReachRoute
  '/roadmap': typeof RoadmapRoute
  '/studio': typeof StudioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/agents': typeof AuthenticatedDashboardAgentsRoute
  '/_authenticated/dashboard/discover': typeof AuthenticatedDashboardDiscoverRoute
  '/_authenticated/dashboard/liquidity': typeof AuthenticatedDashboardLiquidityRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRouteWithChildren
  '/_authenticated/dashboard/portfolio': typeof AuthenticatedDashboardPortfolioRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/proofs': typeof AuthenticatedDashboardProofsRouteWithChildren
  '/_authenticated/dashboard/stats': typeof AuthenticatedDashboardStatsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/orders/$orderId': typeof AuthenticatedDashboardOrdersOrderIdRoute
  '/_authenticated/dashboard/proofs/$proofId': typeof AuthenticatedDashboardProofsProofIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/journal'
    | '/reach'
    | '/roadmap'
    | '/studio'
    | '/dashboard'
    | '/dashboard/agents'
    | '/dashboard/discover'
    | '/dashboard/liquidity'
    | '/dashboard/orders'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/proofs'
    | '/dashboard/stats'
    | '/dashboard/'
    | '/dashboard/orders/$orderId'
    | '/dashboard/proofs/$proofId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/journal'
    | '/reach'
    | '/roadmap'
    | '/studio'
    | '/dashboard/agents'
    | '/dashboard/discover'
    | '/dashboard/liquidity'
    | '/dashboard/orders'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/proofs'
    | '/dashboard/stats'
    | '/dashboard'
    | '/dashboard/orders/$orderId'
    | '/dashboard/proofs/$proofId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/journal'
    | '/reach'
    | '/roadmap'
    | '/studio'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/agents'
    | '/_authenticated/dashboard/discover'
    | '/_authenticated/dashboard/liquidity'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/portfolio'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/proofs'
    | '/_authenticated/dashboard/stats'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/orders/$orderId'
    | '/_authenticated/dashboard/proofs/$proofId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  ReachRoute: typeof ReachRoute
  RoadmapRoute: typeof RoadmapRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/stats': {
      id: '/_authenticated/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof AuthenticatedDashboardStatsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/proofs': {
      id: '/_authenticated/dashboard/proofs'
      path: '/proofs'
      fullPath: '/dashboard/proofs'
      preLoaderRoute: typeof AuthenticatedDashboardProofsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/portfolio': {
      id: '/_authenticated/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof AuthenticatedDashboardPortfolioRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/liquidity': {
      id: '/_authenticated/dashboard/liquidity'
      path: '/liquidity'
      fullPath: '/dashboard/liquidity'
      preLoaderRoute: typeof AuthenticatedDashboardLiquidityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/discover': {
      id: '/_authenticated/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof AuthenticatedDashboardDiscoverRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agents': {
      id: '/_authenticated/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/proofs/$proofId': {
      id: '/_authenticated/dashboard/proofs/$proofId'
      path: '/$proofId'
      fullPath: '/dashboard/proofs/$proofId'
      preLoaderRoute: typeof AuthenticatedDashboardProofsProofIdRouteImport
      parentRoute: typeof AuthenticatedDashboardProofsRoute
    }
    '/_authenticated/dashboard/orders/$orderId': {
      id: '/_authenticated/dashboard/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedDashboardOrdersRoute
    }
  }
}

interface AuthenticatedDashboardOrdersRouteChildren {
  AuthenticatedDashboardOrdersOrderIdRoute: typeof AuthenticatedDashboardOrdersOrderIdRoute
}

const AuthenticatedDashboardOrdersRouteChildren: AuthenticatedDashboardOrdersRouteChildren =
  {
    AuthenticatedDashboardOrdersOrderIdRoute:
      AuthenticatedDashboardOrdersOrderIdRoute,
  }

const AuthenticatedDashboardOrdersRouteWithChildren =
  AuthenticatedDashboardOrdersRoute._addFileChildren(
    AuthenticatedDashboardOrdersRouteChildren,
  )

interface AuthenticatedDashboardProofsRouteChildren {
  AuthenticatedDashboardProofsProofIdRoute: typeof AuthenticatedDashboardProofsProofIdRoute
}

const AuthenticatedDashboardProofsRouteChildren: AuthenticatedDashboardProofsRouteChildren =
  {
    AuthenticatedDashboardProofsProofIdRoute:
      AuthenticatedDashboardProofsProofIdRoute,
  }

const AuthenticatedDashboardProofsRouteWithChildren =
  AuthenticatedDashboardProofsRoute._addFileChildren(
    AuthenticatedDashboardProofsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAgentsRoute: typeof AuthenticatedDashboardAgentsRoute
  AuthenticatedDashboardDiscoverRoute: typeof AuthenticatedDashboardDiscoverRoute
  AuthenticatedDashboardLiquidityRoute: typeof AuthenticatedDashboardLiquidityRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRouteWithChildren
  AuthenticatedDashboardPortfolioRoute: typeof AuthenticatedDashboardPortfolioRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardProofsRoute: typeof AuthenticatedDashboardProofsRouteWithChildren
  AuthenticatedDashboardStatsRoute: typeof AuthenticatedDashboardStatsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAgentsRoute: AuthenticatedDashboardAgentsRoute,
    AuthenticatedDashboardDiscoverRoute: AuthenticatedDashboardDiscoverRoute,
    AuthenticatedDashboardLiquidityRoute: AuthenticatedDashboardLiquidityRoute,
    AuthenticatedDashboardOrdersRoute:
      AuthenticatedDashboardOrdersRouteWithChildren,
    AuthenticatedDashboardPortfolioRoute: AuthenticatedDashboardPortfolioRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardProofsRoute:
      AuthenticatedDashboardProofsRouteWithChildren,
    AuthenticatedDashboardStatsRoute: AuthenticatedDashboardStatsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  ReachRoute: ReachRoute,
  RoadmapRoute: RoadmapRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
